### PR TITLE
Add slides for 'Unleashing the power of pathway simulation' Talk 

### PR DESCRIPTION
**Pull request by Bergam0t**
Added link to slides and code for pathway simulation talk from the Friday (2024-11-22_rosser_power_of_pathway_simulation.md).

I've included a couple of extra links to the bottom of the template to make it easier to find key links from the presentation - happy to remove those if preferred!

### CODE REVIEW

**Comment by Lextuga007** [comment]
Links look great 👍🏻 Thanks for adding 😃

**Review by anyaferguson — COMMENTED** [review]
Thanks @Bergam0t. Could you please check the link for the code - it's currently the same as the one for the slides.

**Comment by Bergam0t** [comment]
Oops, apologies! Thanks for picking that up - should now be fixed.

**Comment by anyaferguson** [comment]
Closes #18.

**Pull request merged**
